# Generated by Django 2.1.2 on 2018-10-03 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='remaining_budget',
        ),
    ]
